AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Amazon Connect Operational Review - Serverless Application with SAM

Metadata:
  AWS::ServerlessRepo::Application:
    Name: amazon-connect-operational-review
    Description: Automated operational review for Amazon Connect instances
    Author: AWS
    SemanticVersion: 1.0.0

Globals:
  Function:
    Runtime: python3.13
    Timeout: 300
    MemorySize: 512
    Layers:
      - !Ref SharedLayer
    Environment:
      Variables:
        STORAGE_BACKEND: !Ref StorageBackend
        RESULTS_TABLE: !If
          - UseDynamoDB
          - !Ref ResultsTable
          - 'not-used'
        CONNECT_INSTANCE_ARN: !Ref AmazonConnectInstanceARN
        CONNECT_CW_LOG_GROUP: !Ref AmazonConnectCloudWatchLogGroup
        S3_REPORTING_BUCKET: !If
          - CreateBucket
          - !Ref ReportsBucket
          - !Ref AmazonS3ForReports
        LOG_LEVEL: INFO

Parameters:
  AmazonConnectInstanceARN:
    Type: String
    Description: 'The ARN of your Amazon Connect instance. Example: arn:aws:connect:<region>:<account-id>:instance/<resource-id>'

  AmazonConnectCloudWatchLogGroup:
    Type: String
    Description: 'The CloudWatch Log Group for your Amazon Connect instance. Example: /aws/connect/connect-instance-name'

  CreateS3Bucket:
    Type: String
    Description: 'Create a new S3 bucket for reports? Choose "Yes" to create, "No" to use existing bucket'
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'

  AmazonS3ForReports:
    Type: String
    Description: 'S3 Bucket name for reports. Leave empty for auto-generated name (if CreateS3Bucket=Yes). If CreateS3Bucket=No, must specify existing bucket name.'
    Default: 'auto-generated'

  ReviewSchedule:
    Type: String
    Description: 'Schedule for automated reviews (cron expression). Default: Weekly on Monday at 9 AM UTC'
    Default: 'cron(0 9 ? * MON *)'

  StorageBackend:
    Type: String
    Description: 'Storage backend for intermediate results. S3 (default, lower cost) or DynamoDB (faster queries, historical data)'
    Default: 's3'
    AllowedValues:
      - 's3'
      - 'dynamodb'

Conditions:
  CreateBucket: !Equals [!Ref CreateS3Bucket, 'Yes']
  UseAutoGeneratedName: !Equals [!Ref AmazonS3ForReports, 'auto-generated']
  UseDynamoDB: !Equals [!Ref StorageBackend, 'dynamodb']

Resources:
  # Lambda Layer for shared utilities
  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub '${AWS::StackName}-shared-layer'
      Description: Shared utilities for Amazon Connect Operational Review
      ContentUri: functions/shared/
      CompatibleRuntimes:
        - python3.13
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.13

  # S3 Bucket for reports (conditionally created)
  ReportsBucket:
    Type: AWS::S3::Bucket
    Condition: CreateBucket
    Properties:
      BucketName: !If
        - UseAutoGeneratedName
        - !Sub '${AWS::StackName}-reports-${AWS::AccountId}'
        - !Ref AmazonS3ForReports
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldReports
            Status: Enabled
            ExpirationInDays: 90
            NoncurrentVersionExpirationInDays: 30
          - Id: DeleteOldIntermediateResults
            Status: Enabled
            Prefix: reviews/
            ExpirationInDays: 7
            NoncurrentVersionExpirationInDays: 1
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Purpose
          Value: AmazonConnectOperationalReview
        - Key: ManagedBy
          Value: SAM

  # DynamoDB table to store intermediate results (only created when using DynamoDB backend)
  ResultsTable:
    Type: AWS::DynamoDB::Table
    Condition: UseDynamoDB
    Properties:
      TableName: !Sub '${AWS::StackName}-results'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: reviewId
          AttributeType: S
        - AttributeName: componentType
          AttributeType: S
      KeySchema:
        - AttributeName: reviewId
          KeyType: HASH
        - AttributeName: componentType
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      SSESpecification:
        SSEEnabled: true
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

  # Shared IAM role for analyzer functions
  AnalyzerFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonConnectReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSCloudTrail_ReadOnlyAccess
        - arn:aws:iam::aws:policy/ServiceQuotasReadOnlyAccess
        - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
      Policies:
        - PolicyName: S3IntermediateStorage
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub 
                    - 'arn:aws:s3:::${BucketName}/reviews/*'
                    - BucketName: !If
                        - CreateBucket
                        - !Ref ReportsBucket
                        - !Ref AmazonS3ForReports
                  - !Sub 
                    - 'arn:aws:s3:::${BucketName}'
                    - BucketName: !If
                        - CreateBucket
                        - !Ref ReportsBucket
                        - !Ref AmazonS3ForReports
        - PolicyName: PinpointPhoneValidation
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: mobiletargeting:PhoneNumberValidate
                Resource: '*'
        - PolicyName: LogsInsightsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:StartQuery
                  - logs:GetQueryResults
                  - logs:StopQuery
                Resource: '*'

  # DynamoDB access policy (conditionally attached)
  AnalyzerDynamoDBPolicy:
    Type: AWS::IAM::Policy
    Condition: UseDynamoDB
    Properties:
      PolicyName: DynamoDBAccess
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:PutItem
              - dynamodb:GetItem
              - dynamodb:Query
              - dynamodb:Scan
            Resource: !GetAtt ResultsTable.Arn
      Roles:
        - !Ref AnalyzerFunctionRole

  # Orchestrator Lambda - coordinates the review process
  OrchestratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-orchestrator'
      CodeUri: functions/orchestrator/
      Handler: app.lambda_handler
      Timeout: 900
      Role: !GetAtt OrchestratorFunctionRole.Arn
      Environment:
        Variables:
          QUOTA_ANALYZER_FUNCTION: !GetAtt QuotaAnalyzerFunction.Arn
          METRICS_ANALYZER_FUNCTION: !GetAtt MetricsAnalyzerFunction.Arn
          PHONE_ANALYZER_FUNCTION: !GetAtt PhoneAnalyzerFunction.Arn
          FLOW_ANALYZER_FUNCTION: !GetAtt FlowAnalyzerFunction.Arn
          CLOUDTRAIL_ANALYZER_FUNCTION: !GetAtt CloudTrailAnalyzerFunction.Arn
          LOG_ANALYZER_FUNCTION: !GetAtt LogAnalyzerFunction.Arn
          REPORT_GENERATOR_FUNCTION: !GetAtt ReportGeneratorFunction.Arn
      Events:
        ScheduledReview:
          Type: Schedule
          Properties:
            Schedule: !Ref ReviewSchedule
            Description: Automated Amazon Connect operational review
            Enabled: true

  OrchestratorFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: InvokeFunctions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource:
                  - !GetAtt QuotaAnalyzerFunction.Arn
                  - !GetAtt MetricsAnalyzerFunction.Arn
                  - !GetAtt PhoneAnalyzerFunction.Arn
                  - !GetAtt FlowAnalyzerFunction.Arn
                  - !GetAtt CloudTrailAnalyzerFunction.Arn
                  - !GetAtt LogAnalyzerFunction.Arn
                  - !GetAtt ReportGeneratorFunction.Arn

  # DynamoDB access policy for orchestrator (conditionally attached)
  OrchestratorDynamoDBPolicy:
    Type: AWS::IAM::Policy
    Condition: UseDynamoDB
    Properties:
      PolicyName: DynamoDBAccess
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:PutItem
              - dynamodb:GetItem
              - dynamodb:Query
              - dynamodb:UpdateItem
            Resource: !GetAtt ResultsTable.Arn
      Roles:
        - !Ref OrchestratorFunctionRole

  # Quota Analyzer - analyzes service quotas and usage
  QuotaAnalyzerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-quota-analyzer'
      CodeUri: functions/quota_analyzer/
      Handler: app.lambda_handler
      Role: !GetAtt AnalyzerFunctionRole.Arn

  # Metrics Analyzer - analyzes CloudWatch metrics
  MetricsAnalyzerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-metrics-analyzer'
      CodeUri: functions/metrics_analyzer/
      Handler: app.lambda_handler
      Role: !GetAtt AnalyzerFunctionRole.Arn

  # Phone Analyzer - analyzes phone numbers and carriers
  PhoneAnalyzerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-phone-analyzer'
      CodeUri: functions/phone_analyzer/
      Handler: app.lambda_handler
      Role: !GetAtt AnalyzerFunctionRole.Arn

  # Flow Analyzer - analyzes contact flows
  FlowAnalyzerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-flow-analyzer'
      CodeUri: functions/flow_analyzer/
      Handler: app.lambda_handler
      Role: !GetAtt AnalyzerFunctionRole.Arn

  # CloudTrail Analyzer - analyzes API throttling from CloudTrail
  CloudTrailAnalyzerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-cloudtrail-analyzer'
      CodeUri: functions/cloudtrail_analyzer/
      Handler: app.lambda_handler
      Role: !GetAtt AnalyzerFunctionRole.Arn

  # Log Analyzer - analyzes contact flow errors from CloudWatch Logs
  LogAnalyzerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-log-analyzer'
      CodeUri: functions/log_analyzer/
      Handler: app.lambda_handler
      Timeout: 600  # Longer timeout for Log Insights queries
      Role: !GetAtt AnalyzerFunctionRole.Arn

  # Report Generator - consolidates results and generates HTML report
  ReportGeneratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-report-generator'
      CodeUri: functions/report_generator/
      Handler: app.lambda_handler
      Timeout: 300
      Role: !GetAtt ReportGeneratorFunctionRole.Arn

  ReportGeneratorFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ConnectReadAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - connect:DescribeInstance
                  - ds:DescribeDirectories
                Resource: '*'
        - PolicyName: S3IntermediateStorage
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub 
                    - 'arn:aws:s3:::${BucketName}/reviews/*'
                    - BucketName: !If
                        - CreateBucket
                        - !Ref ReportsBucket
                        - !Ref AmazonS3ForReports
                  - !Sub 
                    - 'arn:aws:s3:::${BucketName}'
                    - BucketName: !If
                        - CreateBucket
                        - !Ref ReportsBucket
                        - !Ref AmazonS3ForReports
        - PolicyName: S3Upload
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: s3:PutObject
                Resource: !Sub 
                  - 'arn:aws:s3:::${BucketName}/*'
                  - BucketName: !If
                      - CreateBucket
                      - !Ref ReportsBucket
                      - !Ref AmazonS3ForReports

  # DynamoDB access policy for report generator (conditionally attached)
  ReportGeneratorDynamoDBPolicy:
    Type: AWS::IAM::Policy
    Condition: UseDynamoDB
    Properties:
      PolicyName: DynamoDBAccess
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:Query
              - dynamodb:Scan
            Resource: !GetAtt ResultsTable.Arn
      Roles:
        - !Ref ReportGeneratorFunctionRole

Outputs:
  OrchestratorFunctionArn:
    Description: ARN of the orchestrator Lambda function
    Value: !GetAtt OrchestratorFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-OrchestratorArn'

  ResultsTableName:
    Condition: UseDynamoDB
    Description: DynamoDB table for storing review results (only created when using DynamoDB backend)
    Value: !Ref ResultsTable
    Export:
      Name: !Sub '${AWS::StackName}-ResultsTable'

  ReportBucket:
    Description: S3 bucket for operational review reports
    Value: !If
      - CreateBucket
      - !Ref ReportsBucket
      - !Ref AmazonS3ForReports
    Export:
      Name: !Sub '${AWS::StackName}-ReportBucket'

  ReportBucketCreated:
    Description: Whether the S3 bucket was created by this stack
    Value: !If
      - CreateBucket
      - 'Yes - Bucket created by SAM'
      - 'No - Using existing bucket'
